/* AUTH API */
export const CLEAR_MESSAGES = 'CLEAR_MESSAGES';
export const LOGGING_IN = 'LOGGING_IN';
export const LOGGED_IN = 'LOGGED_IN';
export const LOGGED_OUT = 'LOGGED_OUT';
export const LOGOUT = 'LOGOUT';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const PING_SUCCESS = 'PING_SUCCESS';
export const PING_START = 'PING_START';
/* MESSAGES API */
export const GET_MESSAGES = 'GET_MESSAGES';
export const GET_MESSAGES_START = 'GET_MESSAGES_START';
export const GET_MESSAGES_SUCCESS = 'GET_MESSAGES_SUCCESS';
export const GET_MESSAGES_FAILED = 'GET_MESSAGES_FAILED';
export const MARK_AS_READ = 'MARK_AS_READ';
export const MARKED_AS_READ = 'MARKED_AS_READ';
export const MARK_AS_READ_FAILED = 'MARK_AS_READ_FAILED';
/* SUBSCRIBE API */
export const UNSUBSCRIBE_SUCCESS = 'UNSUBSCRIBE_SUCCESS';
export const SUBSCRIBE_SUCCESS = 'SUBSCRIBE_SUCCESS';
export const SUBSCRIBE = 'SUBSCRIBE';
export const UNSUBSCRIBE = 'UNSUBSCRIBE';
export const PROCESS = 'PROCESS';
export const FAILED = 'FAILED';
/* ACCOUNT API */
export const EDIT_LICENCE_NUMBER = 'EDIT_LICENCE_NUMBER';
export const EDIT_LICENCE_NUMBER_SUCCESS = 'EDIT_LICENCE_NUMBER_SUCCESS';
export const EDIT_LICENCE_NUMBER_FAILED = 'EDIT_LICENCE_NUMBER_FAILED';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAILED = 'CHANGE_PASSWORD_FAILED';
/* HISTORY */
export const FETCH_LAST_DRAW = 'FETCH_LAST_DRAW';
export const FETCH_LAST_DRAW_SUCCESS = 'FETCH_LAST_DRAW_SUCCESS';
export const FETCH_LAST_DRAW_FAILED = 'FETCH_LAST_DRAW_FAILED';
/* MANAGE USERS */
export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILED = 'FETCH_USERS_FAILED';
export const SEARCH_USERS = 'SEARCH_USERS';
export const SEARCH_USERS_SUCCESS = 'SEARCH_USERS_SUCCESS';
export const SEARCH_USERS_FAILED = 'SEARCH_USERS_FAILED';
export const USER_OPERATION_FAILED = 'USER_OPERATION_FAILED';
export const USER_OPERATION_SUCCESS = 'USER_OPERATION_SUCCESS';
export const UPDATE_USER = 'UPDATE_USER';
export const CREATE_USER = 'CREATE_USER';
export const DELETE_USER = 'DELETE_USER';
/* MANAGE CARDS */
export const FETCH_CARDS = 'FETCH_CARDS';
export const FETCH_CARDS_FAILED = 'FETCH_CARDS_FAILED';
export const FETCH_CARDS_SUCCESS = 'FETCH_CARDS_SUCCESS';
export const SEARCH_CARDS = 'SEARCH_CARDS';
export const SEARCH_CARDS_SUCCESS = 'SEARCH_CARDS_SUCCESS';
export const SEARCH_CARDS_FAILED = 'SEARCH_CARDS_FAILED';
export const CARD_OPERATION_FAILED = 'CARD_OPERATION_FAILED';
export const CARD_OPERATION_SUCCESS = 'CARD_OPERATION_SUCCESS';
export const UPDATE_CARD = 'UPDATE_CARD';
export const CREATE_CARD = 'CREATE_CARD';
export const DELETE_CARD = 'DELETE_CARD';
