/* AUTH API */
export const LOGGING_IN = 'LOGGING_IN';
export const LOGGED_IN = 'LOGGED_IN';
export const LOGGED_OUT = 'LOGGED_OUT';
export const LOGOUT = 'LOGOUT';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const PING_SUCCESS = 'PING_SUCCESS';
export const PING_START = 'PING_START';
/* MESSAGES API */
export const GET_MESSAGES = 'GET_MESSAGES';
export const GET_MESSAGES_START = 'GET_MESSAGES_START';
export const GET_MESSAGES_SUCCESS = 'GET_MESSAGES_SUCCESS';
export const GET_MESSAGES_FAILED = 'GET_MESSAGES_FAILED';
export const MARK_AS_READ = 'MARK_AS_READ';
export const MARKED_AS_READ = 'MARKED_AS_READ';
export const MARK_AS_READ_FAILED = 'MARK_AS_READ_FAILED';
/* SUBSCRIBE API */
export const UNSUBSCRIBE_SUCCESS = 'UNSUBSCRIBE_SUCCESS';
export const SUBSCRIBE_SUCCESS = 'SUBSCRIBE_SUCCESS';
export const SUBSCRIBE = 'SUBSCRIBE';
export const UNSUBSCRIBE = 'UNSUBSCRIBE';
export const PROCESS = 'PROCESS';
export const FAILED = 'FAILED';
